// <auto-generated />
namespace PropertyLogic.Migrations_Property
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InitialPropertyPush : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialPropertyPush));
        
        string IMigrationMetadata.Id
        {
            get { return "201412140255285_InitialPropertyPush"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
